## numpy

In [16]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [18]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
l=range(100)
%timeit [1**2 for i in l]

2.6 µs ± 55.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
a=np.arange(100)
%timeit a**2

623 ns ± 22.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [26]:
a=np.arange(100)
%timeit a**2

609 ns ± 9.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# creating arrays

In [27]:
a=np.array([1,2,3,4])# 1 dimesion
print(a.ndim)

1


In [35]:
b=np.array([[1,2,3,],[5,6,7]])# 2d
print(b.ndim)
print(b)

2
[[1 2 3]
 [5 6 7]]


In [36]:
c=np.array([[[1,2],[3,4],[5,6]]])# 3d
print(c.ndim)

3


In [37]:
print(a.shape)

(4,)


In [38]:
print(b.shape)

(2, 3)


In [39]:
print(c.shape)

(1, 3, 2)


## functions for creating array

In [44]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np
a=np.array([1,10,2])
print(a)

[ 1 10  2]


In [48]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [49]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [54]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## basic data types

In [3]:
import numpy as np
a=np.array(10)
print(a.dtype)

int32


In [7]:
a=np.arange(10,dtype="float64")
print(a.dtype)


float64


In [9]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# # other datatype

In [10]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [11]:
a=np.array([True,False])
print(a.dtype)

bool


In [12]:
a=np.array(["niha","sri niha"])
print(a.dtype)

<U8


## indexing and string

In [13]:
a=np.arange(10)
print(a[5])

5


In [15]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [16]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [17]:
a=np.arange(10)# slicing
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(a[1:8:2])

[1 3 5 7]


In [21]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

## copies and viewing

In [23]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [26]:
print(np.shares_memory(a,b))
b[0]=10
print(a)
print(b)

True
[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [27]:
a=np.arange(10)
b=a[::2].copy# force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
<built-in method copy of numpy.ndarray object at 0x000001E3E4BAFB70>


In [28]:
print(np.shares_memory(a,b))

False


## random number generator

In [32]:
a=np.random.randint(0,20,15)
print(a)

[14 18 13  6  4  3 12 15 15  1 17 11 12 17  7]


In [33]:
mask=(a%2==0)
mask_a=a[mask]
print(mask_a)

[14 18  6  4 12 12]


### basic operations

In [35]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [36]:
print(a*1)

[1 2 3 4]


In [37]:
print(a-1)

[0 1 2 3]


In [38]:
print(a/1)

[1. 2. 3. 4.]


In [39]:
print(a**2)

[ 1  4  9 16]


### all arthemetic operations

In [40]:
b=np.ones(4)+1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [41]:
print(a**2)

[ 1  4  9 16]


In [42]:
print(a+b)

[3. 4. 5. 6.]


In [43]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [44]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


### comparision operator

In [45]:
a=np.array([1,2,3,4])
b=np.array([3,2,5,6])
print(a==b)

[False  True False False]


In [46]:
a=np.array([1,2,3,4])
b=np.array([3,2,5,6])
c=np.array([7,4,8,6])
print(np.array_equal(a,b))

False


In [47]:
print(np.array_equal(a,c))

False


### logical operators

In [48]:
a=np.array([1,0,1,0], dtype="bool")
b=np.array([1,1,0,0], dtype="bool")
print(np.logical_or(a,b))



[ True  True  True False]


In [49]:
print(np.logical_and(a,b))

[ True False False False]


### trignometry

In [50]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [52]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [53]:
np.log(a)

C:\Users\mouni\AppData\Local\Temp\ipykernel_13796\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [54]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


### basic reductions

In [55]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [56]:
x=np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [59]:
x.sum(axis=0)

array([4, 6])

In [60]:
x.sum(axis=1)

array([3, 7])